import { useState } from "react";
import { Document, Page, Text, View, StyleSheet, pdf, Font } from "@react-pdf/renderer";
import { FileDown, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { AnswerData } from "./AnswerPanel";
import { useAuth } from "@/hooks/useAuth";

const styles = StyleSheet.create({
  page: { paddingTop: 48, paddingBottom: 64, paddingHorizontal: 48, fontSize: 10, fontFamily: "Helvetica", color: "#0f172a" },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", borderBottomWidth: 1, borderBottomColor: "#cbd5e1", paddingBottom: 10, marginBottom: 18 },
  brand: { fontSize: 14, fontWeight: 700, color: "#0f172a" },
  brandSub: { fontSize: 9, color: "#64748b", marginTop: 2 },
  meta: { fontSize: 9, color: "#64748b", textAlign: "right" },
  sectionLabel: { fontSize: 8, fontWeight: 700, color: "#475569", letterSpacing: 1, textTransform: "uppercase", marginBottom: 6 },
  queryCard: { backgroundColor: "#f1f5f9", borderLeftWidth: 3, borderLeftColor: "#3b82f6", padding: 12, marginBottom: 18, borderRadius: 2 },
  queryText: { fontSize: 11, fontWeight: 700, lineHeight: 1.4, color: "#0f172a" },
  para: { marginBottom: 8, lineHeight: 1.55, fontSize: 10 },
  confidenceBadge: { fontSize: 8, fontWeight: 700, padding: 3, borderRadius: 2, marginBottom: 12, alignSelf: "flex-start" },
  sourceItem: { marginBottom: 10, paddingLeft: 14, borderLeftWidth: 1, borderLeftColor: "#cbd5e1" },
  sourceHead: { fontSize: 9, fontWeight: 700, marginBottom: 2 },
  sourceRef: { fontSize: 8, color: "#64748b", marginBottom: 3 },
  sourceExcerpt: { fontSize: 9, fontStyle: "italic", lineHeight: 1.45, color: "#334155" },
  footnote: { fontSize: 8, color: "#64748b", marginBottom: 2 },
  footer: { position: "absolute", bottom: 24, left: 48, right: 48, borderTopWidth: 1, borderTopColor: "#cbd5e1", paddingTop: 8, flexDirection: "row", justifyContent: "space-between", fontSize: 8, color: "#64748b" },
});

interface PDFDocProps {
  data: AnswerData;
  user: { name: string; email: string; role: string };
  exportedAt: string;
}

const PDFDoc = ({ data, user, exportedAt }: PDFDocProps) => {
  const confidenceColor =
    data.confidence === "high" ? "#16a34a" : data.confidence === "medium" ? "#d97706" : "#dc2626";
  const paragraphs = data.answer.split(/\n\n+/).filter(Boolean);

  return (
    <Document title={`RIE Export — ${exportedAt}`} author={user.name}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header} fixed>
          <View>
            <Text style={styles.brand}>Regulatory Insight Engine</Text>
            <Text style={styles.brandSub}>IFRS 9 · CRR · Basel · EBA</Text>
          </View>
          <View>
            <Text style={styles.meta}>Esportato: {exportedAt}</Text>
            <Text style={styles.meta}>Utente: {user.name} ({user.role})</Text>
            <Text style={styles.meta}>{user.email}</Text>
          </View>
        </View>

        <Text style={styles.sectionLabel}>Domanda</Text>
        <View style={styles.queryCard}>
          <Text style={styles.queryText}>{data.question}</Text>
        </View>

        <Text style={styles.sectionLabel}>Risposta</Text>
        <Text style={[styles.confidenceBadge, { color: confidenceColor, borderWidth: 1, borderColor: confidenceColor }]}>
          {data.confidence.toUpperCase()} CONFIDENCE
        </Text>
        {paragraphs.map((p, i) => (
          <Text key={i} style={styles.para}>{p}</Text>
        ))}

        {data.sources.length > 0 && (
          <View wrap={false} style={{ marginTop: 14 }}>
            <Text style={styles.sectionLabel}>Fonti citate</Text>
            {data.sources.map((s, i) => (
              <View key={s.id} style={styles.sourceItem} wrap={false}>
                <Text style={styles.sourceHead}>[{i + 1}] {s.document}</Text>
                <Text style={styles.sourceRef}>{s.reference} · p.{s.page} · rilevanza {(s.score * 100).toFixed(0)}%</Text>
                <Text style={styles.sourceExcerpt}>"{s.excerpt}"</Text>
              </View>
            ))}
          </View>
        )}

        <View style={{ marginTop: 18 }}>
          <Text style={styles.footnote}>Modello: {data.model}</Text>
          <Text style={styles.footnote}>Generato: {data.generatedAt}</Text>
        </View>

        <View style={styles.footer} fixed>
          <Text>Generated by Regulatory Insight Engine · For internal use only · Not legal advice</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
};

const fileName = () => {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `RIE_export_${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}.pdf`;
};

export const ExportPDF = ({ data }: { data: AnswerData }) => {
  const [busy, setBusy] = useState(false);
  const { user, profile, role } = useAuth();

  const handleExport = async () => {
    setBusy(true);
    try {
      const u = {
        name: profile?.full_name ?? user?.email?.split("@")[0] ?? "Utente",
        email: user?.email ?? "",
        role: role ?? "analyst",
      };
      const blob = await pdf(
        <PDFDoc data={data} user={u} exportedAt={new Date().toLocaleString("it-IT")} />,
      ).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = fileName();
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } finally {
      setBusy(false);
    }
  };

  return (
    <Button variant="outline" size="sm" className="h-8 gap-1.5 text-xs" onClick={handleExport} disabled={busy}>
      {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileDown className="h-3.5 w-3.5" />}
      PDF
    </Button>
  );
};
